PAGE_TITLE: "Langgraph: Build Stateful Agentic AI Graph"
LLM_OPTIONS: 
  - azure_openai
  - ollama
USECASE_OPTIONS: 
  - basic_chatbot
  - chatbot_with_web
  - ai_news
  - blog_generator
MODEL_OPTIONS: 
  - "gpt-4.1-mini"
  - "llama3.2:latest"